services:
  todo-list:
    image: node:24-alpine
    working_dir: /app
    ports:
      - 0.0.0.0:5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
